---
 - name: Add user to docker group
   tags: centos, group
   ansible.builtin.user:
     name: "{{ ansible_user }}"
     groups: docker
     append: true

 - name: newgrp command
   tags: centos, group
   meta: reset_connection
   when: ansible_distribution == "CentOS"

 - name: Pull Docker Image (CentOS)
   tags: image-centos
   docker_image:
     name: "khlvn/web-app:latest"
     source: pull
   when: ansible_distribution == "CentOS"
   
   
 - name: Run Docker Container
   tags: centoscon
   docker_container:
     name: sampleweb
     image: "khlvn/web-app:latest"
     ports:
       - "8080:80"
     state: started
