---
 - name: Add user to docker group
   tags: centos, group
   ansible.builtin.user:
     name: "{{ ansible_user }}"
     groups: docker
     append: true

 - name: Pull Docker Image (CentOS)
   tags: image-centos
   docker_image:
     name: "khlvn/web-app:latest"
     source: pull
   when: ansible_distribution == "CentOS"   
   
