---
- name: Add user to docker group
  ansible.builtin.user:
    name: USERNAME
    groups: docker
    append: true

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection

- name: Build Docker Image (CentOS)
  tags: centos, docker
  docker_image:
    path: ~/*PROTO/Docker/Dockerfile
    name: web-app
    tag: latest
  when: ansible_distribution == "CentOS"
