---
 - name: Add user to docker group
   ansible.builtin.user:
     name: "{{ ansible_user }}"
     groups: docker
     append: true

 - name: Reset ssh connection to allow user changes to affect ansible user
   ansible.builtin.meta:
     reset_connection   

 - name: Pull Docker Image (CentOS)
   tags: docker, centos
   docker_image:
     name: "khlvn/web-app:latest"
     source: pull
   when: ansible_distribution == "CentOS"
