// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1726044292);
user_pref("app.update.lastUpdateTime.region-update-timer", 1726044292);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1726044292);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1726044321);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1726044292);
user_pref("browser.region.update.updated", 1725964783);
user_pref("browser.search.region", "PH");
user_pref("calendar.caldav.googleResync", 1725964781);
user_pref("calendar.list.sortOrder", "1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c");
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.calendar-main-default", true);
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.calendar-main-in-composite", true);
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.disabled", true);
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.name", "Home");
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.type", "storage");
user_pref("calendar.registry.1e5c0ae8-35ef-4aff-8c0e-e2d4dc2c168c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Shanghai");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1726044273499");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1726044292);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240715172621");
user_pref("extensions.lastAppVersion", "115.13.0");
user_pref("extensions.lastPlatformVersion", "115.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"dc440886-6001-4489-acc0-5a1041ab45cc\",\"google@search.mozilla.org\":\"33fdac19-d903-46fa-add5-efb662112b98\",\"ddg@search.mozilla.org\":\"2307dcc4-3b7e-4e20-aa9b-7c2919414800\",\"amazon@search.mozilla.org\":\"25b90d1d-60ae-40de-a2cc-1f8290a6632d\",\"chambers-en-GB@search.mozilla.org\":\"324a6e30-4d80-4921-8554-271ce94cde4f\",\"wikipedia@search.mozilla.org\":\"f77080f3-c15f-46b3-883e-d11c8d7679a4\",\"bing@search.mozilla.org\":\"fdd8b3ee-8b48-4166-ba8c-74b535388ac3\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1726044447);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "0471975a-b51d-41c3-a4d0-98fb865cfe9");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1726044447);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -8991);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1726053287);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1726053287);
user_pref("services.settings.thunderbird.search-config.last_check", 1726053287);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1726053287);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1726044447);
user_pref("toolkit.startup.last_success", 1726044259);
user_pref("toolkit.telemetry.cachedClientID", "b7b3c1b7-346f-43d9-b5d3-88b14190c9b1");
user_pref("toolkit.telemetry.previousBuildID", "20240715172621");
