---
 - name: Add user to docker group
   tags: ubuntu, group
   ansible.builtin.user:
     name: "{{ ansible_user }}"
     groups: docker
     append: true

 - name: Pull Docker Image (Ubuntu)
   tags: image-ubuntu
   docker_image:
     name: "khlvn/web-app:latest"
     source: pull
   when: ansible_distribution == "Ubuntu"   
