---
 - name: Add user to docker group
   tags: ubuntu, group
   ansible.builtin.user:
     name: "{{ ansible_user }}"
     groups: docker
     append: true

 - name: newgrp command
   tags: ubuntu, group
   meta: reset_connection
   when: ansible_distribution == "Ubuntu"
   
 - name: Pull Docker Image (Ubuntu)
   tags: image-ubuntu
   docker_image:
     name: "khlvn/web-app:latest"
     source: pull
   when: ansible_distribution == "Ubuntu"
   
 - name: Run Docker Container
   tags: ubuntucon
   docker_container:
     name: sampleweb
     image: "khlvn/web-app:latest"
     ports:
       - "8080:80"
     state: started
